[template]
owner       = "riak"
mode        = "0644"

src         = "riak.conf.tmpl"
dest        = "/etc/riak/riak.conf"

check_cmd   = "/usr/sbin/riak chkconfig /etc/riak/riak.conf"
reload_cmd  = "/usr/sbin/riak restart"

prefix      = "/riak"